version: "3.8"
name: "workout-plan"

services:
  frontend:
    image: node:18-alpine
    container_name: frontend
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    volumes:
      - ./code/workout-plan/frontend:/home/node/app
    ports:
      - "80:5173"
    command: sh -c "npm install && npm run dev"

  backend:
    image: node:18-alpine
    container_name: backend
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./code/workout-plan/backend:/home/node/app
      - ./data:/home/node/data
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run backend"
